# Generated by Django 4.0.5 on 2022-09-05 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_completedtasks_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTeask',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('source_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('vote_total', models.BigIntegerField(blank=True, default=0, null=True)),
                ('vote_ratio', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tags', models.ManyToManyField(blank=True, to='projects.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='CompletedTasks',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
