# Generated by Django 4.0.5 on 2022-09-05 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_completedteask_delete_completedtasks_delete_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedTeask',
            new_name='CompletedTask',
        ),
    ]
