# Generated by Django 4.0.5 on 2022-09-05 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_completedteask_completedtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtask',
            old_name='demo_link',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='completedtask',
            old_name='title',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='completedtask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='completedtask',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='completedtask',
            name='source_link',
        ),
        migrations.RemoveField(
            model_name='completedtask',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='completedtask',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='completedtask',
            name='vote_total',
        ),
    ]
