# Generated by Django 4.0.5 on 2022-10-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo_link',
            new_name='priority',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
