# Generated by Django 4.0.5 on 2022-10-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_delete_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedTask',
            new_name='CompletedTasks',
        ),
    ]
