# Generated by Django 4.0.5 on 2022-10-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_completedtasks_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtasks',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
