# Generated by Django 4.0.5 on 2022-10-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_completedtasks_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtasks',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
