# Generated by Django 4.1 on 2022-10-21 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_completedtasks_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtasks',
            name='createdDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completedtasks',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
