# Generated by Django 4.1.3 on 2023-01-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_completedtasks_createddate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedTasks',
            new_name='ArchivedProjects',
        ),
        migrations.RenameField(
            model_name='archivedprojects',
            old_name='task',
            new_name='project',
        ),
    ]
